### ISSUE TITLE
There is no 2D-3D fitting?

### ISSUE THREAD

**Issue by eyildiz-ugoe** [mathieuaubry/seeing3Dchairs#5]
I successfully compiled and ran the code but the output (`html/figures/`) is just bounding boxes and a few models as separate images, so where is the 2D-3D fitting of the chair? Where is the precise placement of the chair in the image? 

The output of the code is not what the paper/slide promises.

Or is there another way of running this?

**Comment by mathieuaubry** [comment]
did you look at the html? If I remember correctly, the code doesn't do the
overlap, but once you have the model rendered view and the bbox, it's
trivial to do.

2018-05-16 9:49 GMT+02:00 Erenus Yildiz <notifications@github.com>:

**Comment by eyildiz-ugoe** [comment]
Yes I have seen the HTML. There are different chairs with their respective confidence levels given the scene with the detected chair (bounding box). However, nothing of 2D-3D fitting, which is why people try out the method to see that output in the first place, since it is promised and shown as the output in the paper, slides and the video.

**Comment by mathieuaubry** [comment]
the bbox + model give you the alignment (just overlap the top model with
the image at the position of the bbox and you get all the images of the
paper and video). It doesn't go back to the 3D model / 3D pose, but that's
trivial if you have the model and generated the rendered view, so I don't
really understand your question (and the code is designed to work from the
rendered view because we couldn't release the model + that way you can just
render any model you want).

2018-05-16 13:56 GMT+02:00 Erenus Yildiz <notifications@github.com>:

**Comment by eyildiz-ugoe** [comment]
Well, even the first sentence of the abstract the wording "2D-3D alignment" is mentioned and it is repeated throughout the paper countless times. That's why it comes up when searched, and a reader first expects to see that specific output. And when he does not, it is natural that he informs the writer about it. That's all, There is no question, I am just issuing that it would have been nicer if the advertised view (and the pose information too actually) was also provided as an output.  All other is good, no problem with rendering or whatsoever.  

Thank you for your rapid responses. I am closing the issue.
